exclude: [package.json,package-lock.json]

title: Poolware and Service
description: Pool Chemicals, Filters, Pumps, Parts & Equipment
# google_analytics:

sass:
    style: compressed
    sass_dir: _assets\css
